sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PEiytqdn0dJWRUg0f7wemjJQDPbkg3Yla91dc1ZAq18DoIotl3iAKGF7XjaBRZI4sDgrtXhnXcXtRX0KINKae8zvxy83ydB2x3amA3ByqqU5XCZhzImtgQ4QqS216PKNmi192+gWD7Jo1PHtn7CQYX199J3PfZ3p1dZapBoWUpI5HEiraYkl2xqfCco5nb1MaHacDjhdSobH0+yCqU77VsEHX2Ao4wiWlKblNxcOn8M6VsYge4HxsyzxIs4hRGVmzG/oBSph7EduGrkGwrTZKR0yrNb7d2v80Vt7DkMJ9bIU9gVnuMXqXXb999gyNZxeMZshXKzOHCdYSyVFpmL4z7DueCvXMKv5bH5Bf5PEhZXhH4ZIGN5rAY35XbblS/AX7xNSVT63v9FtwPec0jJTP/dOMJtW0tDRC6gtCqG+5ndTqSo18hae+wtTVNjRM4S7eSSSEp51zeHZ/5CxmmbPZjLjWeC3b2MFUfa65XR7t1cCdeQ8e1J1hd3KbfchH0jxW/i+rAWeUsUulohTqSrH09E5TsaSe5R1Jd10slyVWbNv1kJvOwGRgXX3wrzn8Z3xW2MK9IlGBOpf4JPZAvSYZwfkTjHazWlbfh16ih7iLIFXlfo3/+frjyL+bXs16MoXKDNP1Sed89jRDxTAG2pVex0RdBbzfnwPWCmxqbwjNj0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Personal-Memoirs-of-U.-S.-Grant-Part-5._5864
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy